### ISSUE TITLE
Error with get_timeseries_group loading shef file

### ISSUE THREAD

**Issue by krowvin** [HydrologicEngineeringCenter/SHEF_processing#48]
James got an error trying to load data from input shef file to timeseries for SWF. Looks like line ~220 has older code for talking to `cwms-python`?

- https://github.com/HydrologicEngineeringCenter/SHEF_processing/blob/6afcb1bb5e842c0d1e0847027771bbf1b620adc1/shef/loaders/cda_loader.py#L220-L226

## Input file
```
440 
SRUS54 KLCH 181340
RR3LCH
WxCoder
.A TBLT2 251118 C DH0800/TX 82/TN 64/TA 66/PP 0.00
.A1 EP 0.08/ULD 51/DC2511180735
: Evap:: 2.88
```

# Error Output

```
INFO: 
INFO: Use 'testShefit -h' for help
INFO:
INFO: Reading from C:\Code\winIDP\RR3LCH.txt, press ^D (^Z+Enter on Windows) to exit
INFO:
INFO: ----------------------------------------------------------------------
INFO: Program testShefit version 1.5.2 (25Sep2025) starting up
INFO: ----------------------------------------------------------------------
INFO: CdaLoader v0.5 instatiated
ERROR: KeyError: 'TBLT2.TAIRZX' args = ('TBLT2.TAIRZX',)
ERROR: KeyError: 'TBLT2.TAIRZN' args = ('TBLT2.TAIRZN',)
ERROR: KeyError: 'TBLT2.TAIRZZ' args = ('TBLT2.TAIRZZ',)
ERROR: KeyError: 'TBLT2.PPDRZZ' args = ('TBLT2.PPDRZZ',)
ERROR: KeyError: 'TBLT2.EPDRZZ' args = ('TBLT2.EPDRZZ',)
ERROR: KeyError: 'TBLT2.ULDRZZ' args = ('TBLT2.ULDRZZ',)
Traceback (most recent call last):
  File "C:\Code\testShefit.py", line 8, in <module>
    shef_parser.parse(
  File "AppData\Local\miniconda3\envs\env-cwms\lib\site-packages\shef\shef_parser.py", line 4849, in parse 
    loader.done()
  File "AppData\Local\miniconda3\envs\env-cwms\lib\site-packages\shef\loaders\cda_loader.py", line 415, in done
    super().done()
  File "AppData\Local\miniconda3\envs\env-cwms\lib\site-packages\shef\loaders\base_loader.py", line 180, in done
    self.load_time_series()
  File "AppData\Local\miniconda3\envs\env-cwms\lib\site-packages\shef\loaders\cda_loader.py", line 221, in load_time_series
    shef_group = cwms.get_timeseries_group(
TypeError: get_timeseries_group() got an unexpected keyword argument 'group_office_id'
```
## Crit File

<img width="1533" height="53" alt="Image" src="https://github.com/user-attachments/assets/66f3690c-f754-43df-a914-931cfa3fdcd8" />

## myshefscript.py

```python
shef_parser.parse(
    input_name='''C:\Code\winIDP\RR3LCH.txt''',
    #input_name= r"[https://mydomain.mil/test/RR3LCH.txt"] # This would be really cool
    loader_spec=f"cda[{CDA_URL}][{CDA_API_KEY}]",
    )
```

POC: @SWF-WM

**Comment by jbkolze** [comment]
I think this may actually be due to using an old version of cwms-python -- `group_office_id` should be supported in recent versions.  @krowvin or @SWF-WM, can you verify what version of cwms-python is installed in the runtime environment?  It should work with cwms-python v0.7 or newer.

**Comment by SWF-WM** [comment]
@jbkolze @krowvin 
That fixed the issue. I was running a old version of cwms-python on my local machine.  I am still getting the key errors. The key errors look very similar to our old crit file data.

**Comment by jbkolze** [comment]
@SWF-WM Generally the key errors indicate that the parser can't locate a criteria entry for the given SHEF code, i.e. there's not a corresponding entry in the `SHEF Data Acquisition` time series group.

I would cross-reference your errors with your time series group entries.  If an entry for that SHEF code doesn't exist then the error makes sense.  If there is an entry then we can try to do some troubleshooting.
